[package]
name = "flashcards-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.27"
crossterm = "0.27"
clap = { version = "4.5", features = ["derive"] }
rand = "0.8"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
anyhow = "1.0"

